### ISSUE TITLE
Mentioning

### ISSUE THREAD

**Issue by flashwave** [flashii/sockchat#11]
When someone's username is mentioned have it highlight that message with their name on the client side with an option to disable it if desired.

**Comment by nookls** [comment]
Ok Valid

**Comment by nookls** [comment]
your face is a feature request and not an enhancement

**Comment by Ridorii** [comment]
my mom is a feature request

**Comment by flashwave** [comment]
I'm going to end you all

**Comment by Ridorii** [comment]
Kill self first.

**Comment by flashwave** [comment]
Closed
