### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by Ridorii** [flashii/sockchat#15]
Make a feature so that when the window or tab isnt active, and a message has been sent to the chat, a desktop notification appears.

**Comment by Flappyzor** [comment]
is this actually even possible

**Comment by flashwave** [comment]
https://developer.mozilla.org/en/docs/Web/API/notification
Yes it is.

**Comment by Flappyzor** [comment]
woah thats toobular

**Comment by kamil0** [comment]
this actually sounds pretty dank, but have some form of flood control. or maybe, just for PMs.


Sent from my Verizon Wireless 4G LTE smartphone

<div>-------- Original message --------</div><div>From: bogdin bogdan bogdout <notifications@github.com> </div><div>Date:02/01/2015  15:03  (GMT-05:00) </div><div>To: flashii/sockchat <sockchat@noreply.github.com> </div><div>Subject: Re: [sockchat] Desktop Notifications (#15) </div><div>
</div>woah thats toobular

**Comment by kamil0** [comment]
http://i.krakow.pw/OeRvV.png

Something like this.

**Comment by kamil0** [comment]
On Page Load: Notification.requestPermission();
On PM/Message Receive: var notification = new Notification("Notification title", {body: "notification text"});

**Comment by nookls** [comment]
STOP

**Comment by nookls** [comment]
STOP

**Comment by nookls** [comment]
FUCKING

**Comment by nookls** [comment]
SPAMMING

**Comment by nookls** [comment]
MY

**Comment by nookls** [comment]
INBOX

**Comment by nookls** [comment]
FUCK

**Comment by nookls** [comment]
YOU

**Comment by flashwave** [comment]
OR YOU CAN JUST UNWATCH THE REPOSITORY AND NOT SPAM OURS FUCKING NIGGER 

-----Original Message-----

**Comment by MallocNull** [comment]
Added this a couple commits back; however it only triggers a notification if your name is mentioned.

Something I would like to add still is the ability to set aliases in the settings panel so that it will still trigger, say, if I'm referred to as malloc instead of malloc(NULL);
