### ISSUE TITLE
Name autocomplete

### ISSUE THREAD

**Issue by aleph-nought** [flashii/sockchat#19]
I'd like to see it so when you type in the partial username of someone and press tab, it fills the name in. For example: Fla[TAB] --> Flashwave

**Comment by Ridorii** [comment]
You could just, I don't know. Use the existing feature of clicking the name to have it be inputted into the text box?

**Comment by aleph-nought** [comment]
You're retarded, techno.

**Comment by Ridorii** [comment]
Eat shit?

**Comment by aleph-nought** [comment]
lol

**Comment by flashwave** [comment]
You are retarded actually

**Comment by flashwave** [comment]
didn't mean to close it also i'd recommend changing your email notification settings https://github.com/settings/notifications

**Comment by MallocNull** [comment]
Added in latest commit.
