### ISSUE TITLE
Video Tag

### ISSUE THREAD

**Issue by Flappyzor** [flashii/sockchat#31]
like the image tag except for videos, like being able to embed from youtube or vimeo or whatever, and maybe being able to embed from someones special snowflake uploaded mp4 file over at hacheteeteepee:\\cool.con/hiofwef.mp4

**Comment by aleph-nought** [comment]
there's [video], but you need to enable it in the settings

**Comment by aleph-nought** [comment]
don't think it embeds special snowflake videos though

**Comment by RuMoR0922** [comment]
Currently implemented, but disabled by default. You need to go to the settings icon > 'Enable Video Tag'.

Only issue, it only allows YouTube and you need to put in a video ID or it gets broken.

FEATURE: Allow auto ID grab from YouTube, allow multiple video sources

**Comment by aleph-nought** [comment]
As flash said, it's not exactly ideal to have a video embedded in a fasting moving environment such as a chatroom. That being said, it would be nice to see it embed any video, not just ones from YouTube. However, I believe you would need to change the way BBCode is implemented to make this work.

**Comment by Flappyzor** [comment]
o

**Comment by nookls** [comment]
opopopopopo

**Comment by flashwave** [comment]
Think I might just close this with random's comment.
